Created system-upgrade-controller image and script.
rancher/wins pull request #122
Opened 2022-06-14 16:42 UTC by phillipsj

The script supports traditional way that wins can upgrade itself and
host process containers.

Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>

2022-06-14 16:43 UTC, phillipsj commented
[Linking GH #181](https://github.com/rancher/windows/issues/181)

2022-06-14 16:46 UTC, rosskirkpat requested changes
LGTM other than typo :)

2022-06-14 16:46 UTC, rosskirkpat commented on package/windows/Dockerfile
> +COPY ./nstall.ps1 install.ps1
typo with `nstall.ps1`

2022-06-17 19:57 UTC, phillipsj commented
![image](https://user-images.githubusercontent.com/1568133/174393242-f240c447-4817-4eab-9a31-b3fd7835809f.png)

2022-06-17 19:57 UTC, rosskirkpat approved these changes
LGTM!

2022-06-18 05:08 UTC, merged