implement auto upgrades of wins.exe via the SUC image
rancher/wins pull request #260
Opened 2024-11-14 21:01 UTC by HarrisonWAffel

### Summary
Issue: https://github.com/rancher/rancher/issues/47652

### Problem
The `rancher-wins` system-upgrade-controller image does not automatically upgrade the `wins.exe` binary on the host. This forces users to reprovision Windows nodes in order to obtain the latest version of the `system-agent` and `rancher-wins`, and has resulted in unnecessary changes in Rancher to handle behavior differences between different versions of `rancher-wins`. 

### Solution

This PR introduces a new `host` package which embeds the latest version of `wins.exe` into the SUC image during compilation. When the SUC image runs, it will compare the version of wins installed onto the host (by invoking `c:\Windows\wins.exe --version`) and, if needed, write the embedded version to disk into the required directories (`c:\Windows` & `c:\usr\local\bin`). 

This behavior can be disabled by setting the `CATTLE_WINS_SKIP_BINARY_UPGRADE` environment variable to `true`. This is required when running CI tests which do not fully install `rancher-wins`. 

CI has been updated to cover this behavior during PRs and releases, ensuring that the proper version of `wins.exe` is always embedded into the SUC binary. Additionally, existing tests have been adjusted to ensure that we are tracking the proper exit code of certain commands. 

### Extra Context 

This PR does _not_ handle automatic upgrades of the csiproxy. Additional investigation needs to be done regarding this component.

2025-01-06 17:47 UTC, jiaqiluo requested changes
overall LGTM, left a few comments to confirm some information.

2025-01-06 17:47 UTC, jiaqiluo commented on suc/pkg/host/upgrade.go
> +	}
This might be a silly question, but is it possible that an error returned because the service doesn't exist, especially in the case of a fresh installation? I'm asking to ensure that the logic doesn't introduce any unnecessary failures.

2025-01-06 17:47 UTC, jiaqiluo commented on suc/pkg/host/upgrade.go
> +	err = confirmWinsBinaryVersion(desiredVersion, getWinsUsrLocalBinBinary())
nit
```suggestion
	err = confirmWinsBinaryVersion(desiredVersion,usrLocalBinPath)
```

2025-01-06 17:47 UTC, jiaqiluo commented on suc/pkg/host/upgrade.go
> +	err = os.Remove(updatedBinaryPath)
Why are we removing the source binary here? Could it be possible that the binary at the target location gets removed somehow, and we would need to copy it over again?

2025-01-06 18:52 UTC, HarrisonWAffel commented on suc/pkg/host/upgrade.go
> +	}
That's a good point but my understanding is that scenario can't happen. The node needs to be connected to the cluster before any SUC plans are delivered, which requires the rancher-wins service to be running. However I can add some additional handling just to be safe. In the scenario you're describing the `OpenRancherWinsService` wouldn't fail, but `rw.Stop` would.

2025-01-06 18:53 UTC, jakefhyde reviewed
Just a few minor nits, nothing blocking.

2025-01-06 18:53 UTC, jakefhyde commented on suc/pkg/host/common.go
> +		return "", fmt.Errorf("must specify a path")
IMO I prefer declaring errors as private package variables with `errors.New` so it's easy to write unit tests for them with `errors.Is`. You have some tests for this function that just expect an error being returned, and I know that realistically there isn't much of a use to do so, but personally I like to check the exact error that is being returned if at all possible. I won't block on this, but I've found it's generally a good practice, although it can conflict with writing table style tests.

2025-01-06 18:53 UTC, jakefhyde commented on suc/pkg/host/common.go
> +			return "", fmt.Errorf("provided path (%s) does not exist", path)
Just out of curiosity, what is the purpose for returning this separately as opposed to just using the following return?

2025-01-06 18:53 UTC, jakefhyde commented on suc/pkg/host/upgrade.go
> +	// the binary it uses
```suggestion
	// The service needs to be stopped before we can modify the binary it uses
```

2025-01-06 19:00 UTC, HarrisonWAffel commented on suc/pkg/host/upgrade.go
> +	err = os.Remove(updatedBinaryPath)
The intent here was to ensure that we aren't leaving binaries on the host that aren't being used. Do you mean that it would be useful for users to have access to this file in case they need to manually restore to that version? 

Technically there _are_ two copies of wins.exe on each node, so there is still a backup that can be used to manually update the node if one is deleted. lmk if I've misunderstood your comment though 😄

2025-01-06 19:29 UTC, jiaqiluo commented on suc/pkg/host/upgrade.go
> +	}
sgtm

2025-01-06 19:33 UTC, jiaqiluo commented on suc/pkg/host/upgrade.go
> +	err = os.Remove(updatedBinaryPath)
I was initially considering the case where the function might be invoked again and fail to find the binary because it was removed. However, I now realize that the binary is recreated each time the function is called, so my question is no longer relevant.

2025-01-06 19:34 UTC, jiaqiluo approved these changes

2025-01-06 19:47 UTC, HarrisonWAffel commented on suc/pkg/host/common.go
> +			return "", fmt.Errorf("provided path (%s) does not exist", path)
It's been a while since i first raised this PR, but iirc this resulted in a more useful/readable error message when inspecting the SUC pod logs

2025-01-06 20:13 UTC, HarrisonWAffel commented on suc/pkg/host/common.go
> +		return "", fmt.Errorf("must specify a path")
I agree with the sentiment, however this particular function is tested via the pester integration tests, so we wouldn't be able to leverage new error specific variables. Additionally a lot of the errors include runtime specific information (like paths and whatnot) that we don't know at compile time.

2025-01-07 22:24 UTC, jakefhyde approved these changes

2025-01-07 22:29 UTC, merged